### ISSUE TITLE
Question: Wiring.

### ISSUE THREAD

**Issue by jumper-d-1981** [hugokernel/esphome-weather-station#10]
I know this is not where I need to post this but cannot find anyone else even remotely close to a similar project so please please forgive my ignorance, and posting here.

I am in search of wiring specifics.  That is, I am working on this with my son, and he snipped the ends off both the (direction and speed) rj11 and the (rain bucket) rj11.  AND of course I cannot find them.  We bought the sensor kit from Spark fun, but not the board that accompanies it.  Figuring we would implement it with ESP32 at a future date, but now that date is here, I cannot figure out which wires are which...and thought it would be nice to be sure before experimenting.

It looks like I can tie certain wires to resistors on the + and others to GND, then jump the tied wires to pins to read...but no schematic I have looked at shows what color.

Thanks.

**Comment by geejayem99** [comment]
Usually the wind speed is just a reed switch that closes 1 or 2 times per revolution, so check continuity on sets of 2 wires while rotating the anemometer until you find that. The remaining 2 just switch in different value resistors depending on the direction, so checking resistance on the remaining 2 wires, you should see those values as you rotate the wind direction vane. Rain bucket is also a reed switch, so use the continuity check to figure out which wires connect when you tilt the rain sensor back and forth

**Comment by hugokernel** [comment]
As @geejayem99 said, it's very easy to find the wiring if you have a simple multi-meter in continuity mode, connect to one of the wires and ground, move one of the sensors and you'll see the signal close if you're connected to the right one.

**Comment by Tntdruid** [comment]
@geejayem99 Can you share what color does what?

**Comment by geejayem99** [comment]
No, not easily.

**Comment by geejayem99** [comment]
This page may help. It doesn't mention colours, but has a diagram and description for that particular sensor's wiring for the rain and wind components part way down.
https://learn.sparkfun.com/tutorials/weather-meter-hookup-guide
