### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by worldwidefelix** [hugokernel/esphome-weather-station#2]
Hi. Thank you for sharing awesome code with esphome.

While I am working with wring the wind sensor devices, I am confused with some wiring problem such as resistance, GPIO etc..

Would you upload your whole system's wiring diagram?

**Comment by hugokernel** [comment]
Hi,

As I explain in the article, this project is derived from an article in Elektor magazine (https://www.elektormagazine.com/labs/remake-elektor-weather-station).

The schematics are available on the article page as a PDF:

* https://www.elektormagazine.com/files/attachment/31165
* https://www.elektormagazine.com/files/attachment/23317

**Comment by worldwidefelix** [comment]
Thank you. So, did you follow every wiring step without modification just as diagrams in the files?

**Comment by hugokernel** [comment]
> Thank you. So, did you follow every wiring step without modification just as diagrams in the files?

Yes because I used the original card from the article.
