### ISSUE TITLE
Rain day is less then rain minute

### ISSUE THREAD

**Issue by Martinvdm** [hugokernel/esphome-weather-station#5]
Somehow the rain day sensor is lower then the rain minute sensor.
![D9439FE8-ACBE-4AB7-954B-B42633E01B0C](https://user-images.githubusercontent.com/1952661/152855536-f4055a19-0de5-46e9-b217-a1d9e087baa1.jpeg)
Any idea ?

**Comment by hugokernel** [comment]
Hi,

Sorry for the late reply.

The `rainfall per min` is an integration sensor (https://esphome.io/components/sensor/integration.html) where the `total daily rain` is an total_daily_energy (https://esphome.io/components/sensor/total_daily_energy.html).
If it rains a lot in a short period of time, the value from the integration can increase very quickly.

The important thing is to make sure the accumulation is consistent at the end of the day.

++
