### ISSUE TITLE
Values for wind direction

### ISSUE THREAD

**Issue by Liniik** [hugokernel/esphome-weather-station#9]
I need to use different reference voltage for the wind direction sensor (3.3 V) and I'm struggling with understanding how did you get values for `sensor.in_range`? I looked at the table in manual for the weather station and e.g. north is 33k Ohms but you have 15k - 15.5k Ohms. According to manual for mine version, resistances are the same so I don't know what should I set. Or was it just trial and error?

**Comment by hugokernel** [comment]
I don't really remember, but I think I did the measurements on my station.

I invite you to do the same on yours, so you can be sure you're getting the right values.
